name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: What would you like to improve?
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: What problem would this solve?
    validations:
      required: true
